apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: my-host
spec:
  hostname: {{ambassador_host}}
  acmeProvider:
    authority: none
  tlsSecret:
    name: ambassador-certs
  requestPolicy:
    insecure:
      action: Redirect